'use client';

import { useMemo, useState } from 'react';
import { DataQuality } from './DataQuality';
import { FilterBar } from './FilterBar';
import { KpiCard } from './KpiCard';
import { ProductTable } from './ProductTable';
import { ProfitabilityMap } from './ProfitabilityMap';
import { RecommendationPanel } from './RecommendationPanel';
import { TrendChart } from './TrendChart';
import { WhatChanged } from './WhatChanged';
import { ForecastPanel } from './ForecastPanel';
import { ScenarioSimulator } from './ScenarioSimulator';
import { OpportunityPanel } from './OpportunityPanel';
import type { Artifact, Filters, Recommendation } from '../lib/types';
import type { QualityReport } from '../lib/importer';
import type { DrillFilterKey } from '../lib/decision';
import { ALL, calculateKpis, defaultFilters, filterFacts, formatMoney, formatPercent, monthlySeries, previousPeriodFilters, productSeries, setDisplayCurrency } from '../lib/view';

type Metric = 'revenue' | 'profit' | 'margin';
function delta(current: number, previous: number): number | null { if (!previous) return null; return current / previous - 1; }
function recommendationsForFilters(artifact: Artifact, filters: Filters): Recommendation[] {
  const active: Array<[string, string]> = [['region', filters.region], ['channel', filters.channel], ['customer_segment', filters.segment], ['category', filters.category], ['product', filters.product]].filter(([, value]) => value !== ALL) as Array<[string, string]>;
  const scoped = artifact.recommendations.filter((item) => { if (!item.scope.dimension) return active.length === 0; return active.some(([dimension, value]) => item.scope.dimension === dimension && item.scope.value === value); });
  return scoped.length ? scoped : artifact.recommendations.filter((item) => !item.scope.dimension);
}
function MetricToggle({ metric, onChange }: { metric: Metric; onChange: (metric: Metric) => void }) { return <div className="segmented" role="group" aria-label="Trend metric">{(['revenue', 'profit', 'margin'] as Metric[]).map((item) => <button type="button" aria-pressed={metric === item} className={metric === item ? 'segmented__active' : ''} onClick={() => onChange(item)} key={item}>{item}</button>)}</div>; }

export function Dashboard({ artifact, sourceLabel, quality, onNewDataset }: { artifact: Artifact; sourceLabel: string; quality: QualityReport; onNewDataset: () => void }) {
  const [filters, setFilters] = useState<Filters>(() => defaultFilters(artifact.metadata.date_min, artifact.metadata.date_max));
  const [metric, setMetric] = useState<Metric>('revenue'); const [currency, setCurrency] = useState('USD');
  const filteredFacts = useMemo(() => filterFacts(artifact.records, filters), [artifact.records, filters]);
  const current = useMemo(() => calculateKpis(filteredFacts), [filteredFacts]); const trend = useMemo(() => monthlySeries(filteredFacts), [filteredFacts]); const products = useMemo(() => productSeries(filteredFacts), [filteredFacts]);
  const previous = useMemo(() => { const previousFilters = previousPeriodFilters(filters, artifact.metadata.date_min); return previousFilters ? calculateKpis(filterFacts(artifact.records, previousFilters)) : null; }, [artifact, filters]);
  const scopedRecommendations = recommendationsForFilters(artifact, filters); const activeCount = [filters.region, filters.channel, filters.segment, filters.category, filters.product].filter((value) => value !== ALL).length; const anomalyCount = artifact.anomalies.filter((item) => item.month >= filters.startDate.slice(0, 7) && item.month <= filters.endDate.slice(0, 7)).length; const isUserData = artifact.metadata.build_mode === 'browser_private_upload';

  function drillDown(key: DrillFilterKey, value: string) {
    setFilters((currentFilters) => ({ ...currentFilters, [key]: value }));
    window.requestAnimationFrame(() => document.getElementById('pulse')?.scrollIntoView({ behavior: 'smooth', block: 'start' }));
  }

  return <main>
    <header className="hero" id="overview"><nav className="topnav" aria-label="Primary navigation"><a className="brand" href="#overview"><span className="brand-mark">S</span><span>Signal / Sales Intelligence</span></a><div className="nav-links"><a href="#changes">What changed</a><a href="#opportunities">Opportunities</a><a href="#performance">Performance</a><a href="#forecast">Forecast</a><a href="#scenario">Simulator</a><a href="#recommendations">Actions</a></div></nav><div className="hero-grid"><div><p className="eyebrow">{isUserData ? 'Your business · private browser analysis' : 'Sample company · 100 Days of Data Science'}</p><h1>Sales Analytics<br /><span>Command Center</span></h1><p className="hero-copy">Upload real sales data, understand what changed, rank commercial leakage, investigate anomalies, forecast the next quarter, and test decisions before acting.</p><div className="hero-actions no-print"><button className="button button--light" onClick={onNewDataset}>Analyze another file</button><button className="button button--outline-light" onClick={() => window.print()}>Export executive PDF</button></div></div><div className="hero-status"><div><span className="status-dot status-dot--ok" /><strong>{isUserData ? 'Your file validated' : 'Sample artifact validated'}</strong></div><p><strong>{sourceLabel}</strong></p><p>{artifact.metadata.row_count.toLocaleString()} valid rows · {artifact.metadata.date_min} → {artifact.metadata.date_max}</p><p>Data quality {quality.score}/100 · {quality.rejectedRows.toLocaleString()} rejected rows</p></div></div></header>
    <div className="page-shell"><div className="workspace-banner no-print"><div><span className={`source-badge ${isUserData ? 'source-badge--real' : ''}`}>{isUserData ? 'REAL DATA' : 'DEMO DATA'}</span><strong>{sourceLabel}</strong><span>{isUserData ? 'Processed locally. Your workbook never leaves this browser.' : 'Synthetic demo. Upload your own file to make the analysis operational.'}</span></div><div className="workspace-tools"><label>Currency <select value={currency} onChange={(event) => { setDisplayCurrency(event.target.value); setCurrency(event.target.value); }}><option>USD</option><option>INR</option><option>EUR</option><option>GBP</option><option>AED</option><option>SAR</option><option>JPY</option></select></label><button className="button button--ghost" onClick={onNewDataset}>Change dataset</button></div></div>
      <FilterBar artifact={artifact} filters={filters} onChange={setFilters} onReset={() => setFilters(defaultFilters(artifact.metadata.date_min, artifact.metadata.date_max))} />
      <section className="section" id="pulse"><div className="section-heading"><div><p className="eyebrow">Executive pulse</p><h2>Economics of the selected view</h2></div><p>{filteredFacts.length.toLocaleString()} transaction lines · {activeCount} dimension filters active</p></div>{filteredFacts.length === 0 ? <div className="empty-state">No transactions match the selected filters.</div> : <div className="kpi-grid"><KpiCard label="Net revenue" value={formatMoney(current.revenue)} delta={previous ? delta(current.revenue, previous.revenue) : null} context={`${current.orders.toLocaleString()} orders`} /><KpiCard label="Gross profit" value={formatMoney(current.profit)} delta={previous ? delta(current.profit, previous.profit) : null} context={`${formatPercent(current.margin)} realized margin`} tone="profit" /><KpiCard label="Gross margin" value={formatPercent(current.margin)} delta={previous ? current.margin - previous.margin : null} context={`${formatMoney(current.cost)} cost base`} /><KpiCard label="Discount spend" value={formatMoney(current.discountAmount)} delta={previous ? delta(current.discountAmount, previous.discountAmount) : null} context={`${formatPercent(current.discountRate)} weighted rate`} tone="risk" /><KpiCard label="Average order value" value={formatMoney(current.aov)} delta={previous ? delta(current.aov, previous.aov) : null} context={`${current.units.toLocaleString()} units sold`} /><KpiCard label="Average selling price" value={formatMoney(current.asp)} delta={previous ? delta(current.asp, previous.asp) : null} context="Net revenue per unit" /></div>}</section>
      <section className="section" id="changes"><div className="section-heading"><div><p className="eyebrow">What changed?</p><h2>The management brief before the charts</h2></div><p>Switch between month-over-month and year-over-year, then inspect the exact driver in one click.</p></div><WhatChanged records={filteredFacts} onDrillDown={drillDown} /></section>
      <section className="section" id="opportunities"><div className="section-heading"><div><p className="eyebrow">Priority queue</p><h2>Where management attention is worth spending</h2></div><p>Ranks material discount leakage and margin gaps without pretending every gap is recoverable profit.</p></div><OpportunityPanel records={filteredFacts} onDrillDown={drillDown} /></section>
      <section className="section section--split" id="performance"><div className="panel panel--wide"><div className="panel-heading"><div><p className="eyebrow">Growth & trajectory</p><h2>Monthly performance</h2><p>Hover or focus any month for exact economics; switch metrics to see whether growth becomes profit.</p></div><MetricToggle metric={metric} onChange={setMetric} /></div><TrendChart data={trend} metric={metric} /></div><aside className="panel panel--compact"><p className="eyebrow">Risk monitor</p><h2>{anomalyCount} validated {anomalyCount === 1 ? 'anomaly' : 'anomalies'}</h2><p>MAD robust z-score. A flag means investigate, not cause proven.</p><div className="anomaly-list">{artifact.anomalies.filter((item) => item.month >= filters.startDate.slice(0,7) && item.month <= filters.endDate.slice(0,7)).slice(0,4).map((item) => <div key={`${item.month}-${item.metric}`}><strong>{item.month}</strong><span>{formatMoney(item.value)} · {item.direction} · z {item.robust_z_score.toFixed(2)}</span></div>)}{anomalyCount === 0 && <div className="mini-empty">No month crosses the threshold in this date window.</div>}</div></aside></section>
      <section className="section" id="forecast"><div className="section-heading"><div><p className="eyebrow">Planning signal</p><h2>Next 3 months revenue forecast</h2></div><p>Transparent trend/seasonality forecast with an error band.</p></div><div className="panel"><ForecastPanel records={filteredFacts} /></div></section>
      <section className="section" id="scenario"><div className="section-heading"><div><p className="eyebrow">Decision simulator</p><h2>Test price, discount and cost decisions</h2></div><p>Includes the break-even price move needed to protect current profit under your assumptions.</p></div><div className="panel"><ScenarioSimulator records={filteredFacts} /></div></section>
      <section className="section" id="products"><div className="section-heading"><div><p className="eyebrow">Product intelligence</p><h2>Revenue is not the same as value</h2></div><p>Bubble size = units · benchmark = median product margin · table is sortable</p></div><div className="panel"><ProfitabilityMap rows={products} /></div><div className="panel table-panel"><ProductTable rows={products} onInspect={(product) => drillDown('product', product)} /></div></section>
      <section className="section" id="recommendations"><div className="section-heading"><div><p className="eyebrow">Decision intelligence</p><h2>Computed actions, not canned advice</h2></div><p>{isUserData ? 'Recommendations are recomputed from your uploaded facts.' : 'Sample recommendations come from the analytical pipeline.'}</p></div><RecommendationPanel recommendations={scopedRecommendations} /></section>
      <section className="section" id="quality"><div className="section-heading"><div><p className="eyebrow">Trust layer</p><h2>Data quality & lineage</h2></div></div><DataQuality artifact={artifact} />{quality.warnings.length > 0 && <div className="panel quality-notes"><h3>Upload notes</h3>{quality.warnings.map((warning) => <p key={warning}>• {warning}</p>)}</div>}</section>
      <section className="section methodology"><div className="section-heading"><div><p className="eyebrow">Methodology</p><h2>How the evidence is calculated</h2></div></div><div className="method-grid">{Object.entries(artifact.methodology).map(([key,value]) => <article key={key}><h3>{key.replaceAll('_',' ')}</h3><p>{value}</p></article>)}</div></section>
    </div>
    <footer><span>Day 01 · Sales Intelligence Command Center</span><span>{isUserData ? 'Your data stays in your browser' : 'Demo mode'} · <a href="https://github.com/omparekh54-lgtm/day01-sales-analytics-command-center" target="_blank" rel="noreferrer">GitHub source ↗</a></span></footer>
  </main>;
}
